services:
  db:
    image: postgres:15
    container_name: general_postgres
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: world_db
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always